export {
  AVATAR_DIRECTORY,
  AVATAR_EXTENSION,
  AVATAR_MAX_BYTES,
  AVATAR_MIME_TYPES,
  AVATAR_ROUTE
} from './avatar.config';
export { FREE_CREDITS_AMOUNT, FREE_CREDITS_INTERVAL_MS } from './rewards.config';
